# Autogenerated config.py

# Load the autoconfig.yml file if present
config.load_autoconfig()

# General settings
config.set('colors.webpage.preferred_color_scheme', 'dark')  # Use dark mode for websites when available
config.set('auto_save.session', True)  # Automatically save the session on exit
config.set('content.autoplay', False)  # Disable autoplay of videos
config.set('content.cookies.accept', 'no-3rdparty')  # Accept only first-party cookies
config.set('content.headers.do_not_track', True)  # Send "Do Not Track" header
config.set('content.javascript.clipboard', "access-paste", "https://chatgpt.com")  # Enable JS for specific sites
config.set('content.javascript.enabled', True, 'https://*.trustedsite.com/*')  # Enable JS for specific sites

# Search engines
c.url.searchengines = {
    'DEFAULT': 'https://www.google.com/search?q={}',
    'ddg': 'https://duckduckgo.com/?q={}',
    'wiki': 'https://en.wikipedia.org/wiki/{}',
    'nix': 'https://search.nixos.org/packages?channel=25.05&from=0&size=50&sort=relevance&type=packages&query={}',
    'emo': 'https://emojipedia.org/en/search?q={}'
}

# Key bindings
config.bind(',m', 'spawn mpv {url}')  # Open current page in MPV
config.bind('xb', 'config-cycle statusbar.show always never')  # Toggle statusbar
config.bind('xt', 'config-cycle tabs.show always never')  # Toggle tabs

# Appearance
c.fonts.default_family = 'Fira Code'
c.fonts.default_size = '12pt'
c.colors.completion.fg = '#ffffff'
c.colors.completion.odd.bg = '#2e3440'
c.colors.completion.even.bg = '#3b4252'
c.colors.statusbar.normal.bg = '#3b4252'
c.colors.statusbar.insert.bg = '#81a1c1'
c.colors.statusbar.passthrough.bg = '#88c0d0'
c.colors.statusbar.command.bg = '#4c566a'
c.colors.webpage.bg = "#2e3440"
c.colors.webpage.preferred_color_scheme = "dark"
c.colors.webpage.darkmode.enabled = True


# Tabs
c.tabs.position = 'top'
c.tabs.show = 'always'
c.tabs.favicons.show = 'always'
c.tabs.padding = {'top': 5, 'bottom': 5, 'left': 5, 'right': 5}

# Downloads
c.downloads.location.directory = '~/Downloads'
c.downloads.location.prompt = False  # Download files immediately without prompting

# Privacy
config.set('content.blocking.enabled', True)  # Enable content blocking
config.set('content.blocking.method', 'both')  # Use both Adblock and host blocking
config.set('content.blocking.adblock.lists', [
    'https://easylist.to/easylist/easylist.txt',
    'https://easylist.to/easylist/easyprivacy.txt',
    'https://secure.fanboy.co.nz/fanboy-annoyance.txt'
])

# Miscellaneous
config.set('url.default_page', 'https://news.ycombinator.com/')  # Set start page
config.set('url.start_pages', ['https://google.com'])  # Set start pages

# Enable smooth scrolling
config.set('scrolling.smooth', True)

config.unbind('J')
config.unbind('K')
config.unbind('H')
config.unbind('L')

config.bind('J', 'back')
config.bind('K', 'forward')
config.bind('H', 'tab-prev')
config.bind('L', 'tab-next')

